name: Remote Deploy to EC2

on:
  push:
    branches:
      - main # This will trigger the deployment every time code is pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Navigate to the repository directory
            cd /home/ubuntu/FairPay-ProblemSolvers
            
            # Reset local changes and enforce the latest version from main
            git fetch --all
            git reset --hard origin/main
            
            # Navigate to the backend directory
            cd server
            
            # Install any new dependencies
            npm install
            
            # Restart the PM2 process named 'fairpay-api'
            pm2 restart fairpay-api
